### ISSUE TITLE
merge math guide with main. 

### ISSUE THREAD

**Issue by theloniousgoerz** [MatthewRGonzalez/TeXGuide#5]
Title says it all.

**Comment by MatthewRGonzalez** [comment]
Note that this primary repo only includes the main branch. I can see that your forked copy has commits that are both ahead and behind of main. 

- This may lead to branch conflicts. I always `git pull` in my local before doing any updating. Or see [syncing a fork].(https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork)
- You can open your own PR's to a merge between fork and main, let's keep the issue feature for assignments.
